name: Publish WAR to Nexus

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish-to-nexus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Build the WAR (pom.xml is inside TrainBook folder)
      - name: Build WAR
        working-directory: TrainBook
        run: mvn -B clean package

      # Just to verify WAR is created
      - name: Verify WAR file
        working-directory: TrainBook
        run: ls -l target

      - name: Set version
        run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Publish WAR to Nexus
        working-directory: TrainBook
        run: |
          WAR_FILE=$(ls target/*.war)

          echo "Uploading $WAR_FILE"

          mvn deploy:deploy-file \
            -Durl=${{ secrets.NEXUS_URL }} \
            -DrepositoryId=nexus \
            -Dfile=$WAR_FILE \
            -DgroupId=TrainBook \
            -DartifactId=TrainBook \
            -Dversion=${{ env.VERSION }} \
            -Dpackaging=war \
            -DgeneratePom=true
        env:
          MAVEN_OPTS: "-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true"
